config/routes.rb
Wordcards::Application.routes.draw do
  root to: "cards#index"

  resources :cards

  get "lookup/definition"
  get "lookup/example"
  get "lookup/translation"

  post "tweet/push_cards"
  match "/status" => "status#index"

end

app/models/card.rb
require 'securerandom'
class Card < ActiveRecord::Base
  DEFAULT_IMAGE = 'no-icon.png'

  attr_accessible :definition, :example, :translation, :word, :image_src
  has_and_belongs_to_many :tags
  belongs_to :user

  validates_presence_of :word

  before_create :generate_uuid
  before_save :default_image

  def to_param
    uuid
  end

  private
  def generate_uuid
    self.uuid = SecureRandom.uuid
  end

  def default_image
    self.image_src = DEFAULT_IMAGE if self.image_src.blank?
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  respond_to :html

  before_filter ->{@card = Card.find_by_uuid(params[:id])}, only: [:edit, :update, :show, :destroy]


  def index
    @my_twitter = session[:my_twitter] || '@mytwitter'
    @cards = Card.all.paginate(:page => params[:page])
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(params[:card])
    result = @card.save
    result || (render(action: :new) && return)
    redirect_to :root
  end

  def show
  end

  def edit
  end

  def update
    result = @card.update_attributes(params[:card])
    result || (render(action: :edit) && return)
    redirect_to @card, notice: "Word card was successfully updated"
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end
end

app/controllers/lookup_controller.rb
class LookupController < ApplicationController
  respond_to :json

  def definition
    render :json => {:result => Lookup::Definition.lookup(params[:word])}
  end

  def translation
    render :json => {:result => Lookup::Translation.lookup(params[:word]).join(", ")}
  end

  def example
    render :json => {:result => Lookup::Example.lookup(params[:word]).join(".\n")}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    #twitter_params = {
    #        "oauth_version" => "1.0",
    #        "oauth_nonce" => Time.new.to_i,
    #        "oauth_timestamp" => Time.new.to_s,
    #        "oauth_consumer_key" => ENV['TWITTER_CONSUMER_KEY'],
    #        "oauth_signature_method" => "HMAC-SHA1",
    #        "oauth_signature" => ENV['TWITTER_CONSUMER_SECRET'],
    #        "oauth_callback" => CGI.escapeHTML("http://localhost:3000/")
    #     }

  end

  def create
    #if params[:twitter_anywhere_identity]
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def index
    render text: 'ok'
  end
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
  respond_to :json, :js

  def push_cards
    twitter_account = (session[:my_twitter] = params[:my_twitter])[1..-1]
    Card.all.each do |card|
      #Twitter.update("#{card.word} - view card at http://localhost:3000/cards/#{card.id}")
      begin
        message = "Learn '#{card.word}' - '#{card.translation[0..35]}'. Go to #{card_url(card.uuid)}"
        puts message
        Twitter.d(twitter_account, message)
      rescue Exception => e
        @error ||= ''
        @error += "Failed on card '#{card.word}' - #{e.message}. "
      end

    end

    #p "tweeting cards #{cards.inspect}"

    #Twitter.update("I'm tweeting with @gem!")

    #render :json => {:result => 'ok'}

    @result = 'Card tweets scheduled'

  end

  def card_url(card_uuid)
    "http://#{request.host_with_port}/cards/#{card_uuid}"
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cards/_card_form.html.erb
<div class="form">
<%= form_for(@card) do |f| %>
    <% if @card.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@card.errors.count, "error") %>:</h2>

          <ul>
            <% @card.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :word %><br />
      <%= f.text_field :word %>
      <input type="button" value="Lookup" id="lookup-button" onclick="lookup($('#card_word').val())" />

    </div>
    <div class="field">
      <%= f.label :translation %><br />
      <%= f.text_field :translation %>
    </div>
    <div class="field">
      <%= f.label :definition %><br />
      <%= f.text_area :definition, :size => "60x10" %>
    </div>
    <div class="field">
      <%= f.label :example %><br />
      <%= f.text_area :example, :size => "60x10" %>
    </div>

    <!--<div class="field">-->
      <!--< %= f.label :tags %><br />-->
      <!--< %= f.text_field :tags %>-->
    <!--</div>-->
    <div class="field">
      <%= f.label :image_src, "Enter image url or click on LOOKUP button and choose an image"%><br />
      <%= f.text_field :image_src %>
      <div id="google-images-content"></div>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

</div>

app/views/cards/index.html.erb
<h2>Word Cards</h2>

<div id="container">
  <section class="cards">
    <%= will_paginate @cards %>
    <!--<div class="pagination">-->
      <% @cards.each do |card| %>
        <article class="card">
          <div class="card-thumb front">
            <div class="picture">
              <%= image_tag card.image_src %>
            </div>

            <div class="word">
              <%= link_to card.word, card %>
            </div>

          </div>

          <div class="card-thumb back" style="display: none;">
              <div class="word">
                <strong>Translation:</strong> <%= card.translation %>
              </div>
             <div class="view-card-wrapper">
               <%= link_to 'View Full Card', card, class: 'btn-view-card' %>
             </div>
            <!--<div></div>-->
            <!--< %= link_to card do %>-->

               <!--<div class="word">-->
                  <!--< %= card.translation %>-->
                  <!--&lt;!&ndash;< %= link_to_unless_current card.translation, card %>&ndash;&gt;-->
                <!--</div>-->
            <!--< % end %>-->
          </div>

        </article>
      <% end %>

      <%= link_to(new_card_path) do %>
        <article class="new-card">
          <div class="card-thumb front">
            <div class="picture">
            </div>
            <div class="word">
              new card
            </div>
          </div>
        </article>
      <% end %>


    <!--</div>-->
  </section>



  <div class="menu">



    <br/>
    <%= form_tag tweet_push_cards_path, remote: true, method: :post do %>
      <!--< %= link_to 'Schedule my cards', tweet_push_cards_path(), remote: true, method: :post, class: :btn %>-->
      <%= submit_tag 'Schedule my cards', class: 'btn-fat', onclick: 'toggleSpinner()' %>
      <br/>
      <%= text_field_tag "my_twitter", @my_twitter, style: "width:160px; margin-top: 3px;" %>
    <% end %>
    <br/>
    <p>
      Receive new cards:
    </p>

    <a href="https://twitter.com/gowordcards" class="twitter-follow-button" data-show-count="false" data-size="large"
       data-show-screen-name="false">Follow@gowordcards</a>
    <script>
        !function(d, s, id) {
        var js,fjs = d.getElementsByTagName(s)[0];
        if (!d.getElementById(id)) {
            js = d.createElement(s);
            js.id = id;
            js.src = "//platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js, fjs);
        }
    }(document, "script", "twitter-wjs");
    </script>
    <br/>
    <span id="tweet_result"></span>
    <div id="spinner" style="display:none"><%= image_tag 'spinner.gif' %></div>

  </div>

</div>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>


<div>
  <p>
    <%= label(@card, :word) %>:
  <pre><%= @card.word %></pre>
  </p>

  <p>
    <%= label(@card, :translation) %>:
  <pre><%= @card.translation %></pre>
  </p>

  <p>
    <%= label(@card, :definition) %>:
  <pre><%= @card.definition %></pre>
  </p>

  <p>
    <%= label(@card, :example) %>:
  <pre><%= @card.example %></pre>
  </p>

  <p>
    <%= label(@card, :image_src,  "Image") %>:
  <pre><%= image_tag @card.image_src %></pre>
  </p>
</div>

<%= link_to 'Edit', edit_card_path(@card), class: :btn %> <%= link_to 'Destroy', @card, confirm: 'Are you sure?', method: :delete, class: :btn %>
<br/><br/><br/>
<%= link_to 'Back', cards_path, class: :btn %>


app/views/tweet/push_cards.js.erb
$('#tweet_result').text('<%= escape_javascript(@result) %>').css('color', 'green');
<% if @error %>
    $('#tweet_result').text('<%= escape_javascript(@error) %>').css('color', 'red');
<% end %>
toggleSpinner();